---
apiVersion: v1
kind: Service
metadata:
  name: private-lb-ms-api-pedido
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: techchallenge-microservico-pedido
  ports:
    - protocol: TCP
      port: 80